-- 1. Companies Table
create table if not exists companies (
  ticker varchar(10) primary key,
  name varchar(100) not null,
  sector varchar(100),
  market_type varchar(10),
  desc_summary text,
  updated_at timestamp with time zone default now()
);

-- 2. Financials Table
create table if not exists financials (
  id bigint generated by default as identity primary key,
  ticker varchar(10) references companies(ticker) not null,
  year int not null,
  quarter int not null, -- 0: Yearly, 1-4: Quarterly
  revenue bigint,
  op_profit bigint,
  net_income bigint,
  assets bigint,
  liabilities bigint,
  equity bigint,
  ocf bigint, -- Operating Cash Flow
  is_estimated boolean default false,
  created_at timestamp with time zone default now(),
  unique(ticker, year, quarter)
);

-- 3. Disclosures Table
create table if not exists disclosures (
  rcept_no varchar(20) primary key,
  ticker varchar(10) references companies(ticker) not null,
  report_nm varchar(255) not null,
  rcept_dt date not null,
  flr_nm varchar(100),
  url varchar(255),
  summary_body text, -- Parsed text content
  created_at timestamp with time zone default now()
);

-- 4. Market Daily Table
create table if not exists market_daily (
  id bigint generated by default as identity primary key,
  ticker varchar(10) references companies(ticker) not null,
  date date not null,
  close float,
  open float,
  high float,
  low float,
  volume bigint,
  ma5 float,
  ma20 float,
  ma60 float,
  created_at timestamp with time zone default now(),
  unique(ticker, date)
);

-- Indexing for Performance
create index if not exists idx_financials_ticker on financials(ticker);
create index if not exists idx_disclosures_ticker on disclosures(ticker);
create index if not exists idx_market_daily_ticker on market_daily(ticker);
